spring:
  application:
    name: to-do_list

  datasource:
    url: jdbc:postgresql://localhost:5432/todo_db
    username: postgres
    password: 4567qweR

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    properties:
      hibernate:
        format_sql: true